project_id = "picmyjumulegvtebrdui"

[functions.seed-demo-employees]
verify_jwt = false

[functions.send-daily-timesheet-summary]
verify_jwt = false

[functions.crew-ai-chat]
verify_jwt = false

[functions.send-sick-leave-deadline-notifications]
verify_jwt = false

[functions.invite-employee]
verify_jwt = false

[functions.amu-transcribe-meeting]
verify_jwt = false
